version: '3.7'

services:
  fhirrepo:
    #image: irepo.intersystems.com/intersystems/irishealth:2023.1.4.580.0
    build: .
    init: true
    container_name: ssmixiris
    ports:
       - "8084:1972"
       - "8083:52773"
    environment:
      - TZ=JST-9
    volumes:
      - ./ssmix:/ssmix
